# å˜åŠ¨å‚æ•°ç»Ÿä¸€è®°å½•

#å‚æ•°æ§åˆ¶
parameter:


  #=============================================ğŸ‘‡depğŸ‘‡====================================================
  #ç”Ÿäº§ç¯å¢ƒ

 #     ç”Ÿäº§ç”µè¯å­˜æ”¾åœ°å€
#  excelFile: "D:\\263\\20220608å‹æµ‹ç”µè¯.xlsx"
#      #scp è·å–tokené“¾æ¥
#  url_scp_token: "https://apipcs.263.net/api/getToken"
#
#      #sec è·å–token
#  url_sec_token: "https://meetapitest.263.net/meet/sec/api/getToken"
#
#      #åˆ›å»ºå€¾å¬ç”µè¯ä¼šè®®é“¾æ¥
#  url_create_Meeting: "https://apipcs.263.net/api/createMeeting"
#
#      #è·å–å€¾å¬ç”µè¯ä¼šè®®è¯¦ç»†ä¿¡æ¯é“¾æ¥
#  url_query_Meeting: "https://pcs.263.net/meetingRoom/queryMeetingInfo/"
#
#      #å–æ¶ˆä¼šè®®(åªé’ˆå¯¹æœªå¼€å¯æˆ–å·²è¿‡æœŸå¾—å€¾å¬ä¼šè®®)
#  url_cancelMeeting: "https://apipcs.263.net/api/cancelMeeting"
#
#      #ç»“æŸä¼šè®®
#  url_endMeeting: "https://pcs.263.net/meetingRoom/endMeeting/"
#
#      #
#      #å€¾å¬ç”µè¯ä¼šè®®ä¸»åŠ¨å¤–å‘¼å®¢æˆ·
#  url_callParty: "https://pcs.263.net/meetingRoom/control-callParty"
#
#      #å€¾å¬ç”µè¯ä¼šè®®ä¸»åŠ¨æŒ‚æ–­å¤–å‘¼å®¢æˆ·
#  url_endcallParty: "https://pcs.263.net/meetingRoom/control-endCallParty"
#
#      #å®¢æˆ·UID
#  customerId: "2975223540"
#
#      #å®¢æˆ·å¯†ç 
#  secret: "1Te6hb3be0T924f3"
#
#      #åˆ›å»ºä¼šè®®çš„è´¦æˆ·    å¯†ç   net263
#  userAccount: "kangyao.xue@net263.com"
#
#  cookie: "language=zh; hy_data_2020_id=1812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff; hy_data_2020_js_sdk=%7B%22distinct_id%22%3A%221812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff%22%2C%22site_id%22%3A457%2C%22user_company%22%3A378%2C%22props%22%3A%7B%7D%2C%22device_id%22%3A%221812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff%22%7D; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%221812140eed513-0dd98f2c5bb2d8-26021b51-2073600-1812140eed6766%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%221812140eed513-0dd98f2c5bb2d8-26021b51-2073600-1812140eed6766%22%7D; languageCC=zh; Hm_lvt_d6329c2086ec87a286b0b26a49a301c9=1654120312,1654722435; Qs_lvt_326460=1654120311%2C1654722434; Qs_pv_326460=2535230191188450300%2C4074267285746521600; SESSION=ODhlZjk2OWQtYTE1Ny00ZjE2LTk5YmItNzUwMDQ2Njg4MzU5; i18next=zh; pus=fa96ad10-3c50-4586-bb12-8d89fcb99720"

  #=============================================ğŸ‘†depğŸ‘†====================================================


  #=============================================ğŸ‘‡testğŸ‘‡====================================================
  #æµ‹è¯•ç¯å¢ƒ

  #è™šæ‹Ÿç”µè¯å­˜æ”¾åœ°å€
  #excelFile: "D:\\263\\æµ‹è¯•è™šæ‹Ÿè´¦å·.xlsx"
  excelFile: "F:\\263\\æµ‹è¯•è™šæ‹Ÿç”µè¯.xlsx"

  #è·å–tokené“¾æ¥
  url_scp_token: "https://apipcstest.263.net/api/getToken"

  #åˆ›å»ºå€¾å¬ç”µè¯ä¼šè®®é“¾æ¥
  url_create_Meeting: "https://apipcstest.263.net/api/createMeeting"

  #è·å–å€¾å¬ç”µè¯ä¼šè®®è¯¦ç»†ä¿¡æ¯é“¾æ¥
  url_query_Meeting: "https://pcstest.263.net/meetingRoom/queryMeetingInfo/"

  #å–æ¶ˆä¼šè®®(åªé’ˆå¯¹æœªå¼€å¯æˆ–å·²è¿‡æœŸå¾—å€¾å¬ä¼šè®®)
  url_cancelMeeting: "https://apipcstest.263.net/api/cancelMeeting"

  #ç»“æŸä¼šè®®
  url_endMeeting: "https://pcstest.263.net/meetingRoom/endMeeting/"

  #å€¾å¬ç”µè¯ä¼šè®®ä¸»åŠ¨å¤–å‘¼å®¢æˆ·
  url_callParty: "https://pcstest.263.net/meetingRoom/control-callParty"

  #å€¾å¬ç”µè¯ä¼šè®®ä¸»åŠ¨æŒ‚æ–­å¤–å‘¼å®¢æˆ·
  url_endcallParty: "https://pcstest.263.net/meetingRoom/control-endCallParty"

  #sec è·å–token
  url_sec_token: "https://meetapitest.263.net/meet/sec/api/getToken"

  url_sec_createMeeting: "https://meetapitest.263.net/meet/sec/api/createMeeting"

  url_sec_cancelMeeting: "https://meetapitest.263.net/meet/sec/api/cancelMeeting"

  url_sec_startMeeting: "https://meetingroomtest.263.net/MeetingRoom/control-startMeeting"

  #å®¢æˆ·UID
  customerId: "U10000247885"

  #å®¢æˆ·å¯†ç 
  secret: "123456"

  #åˆ›å»ºä¼šè®®çš„è´¦æˆ·
  userAccount: "xu.chen1@net263.com"

  cookie: "language=zh; languageCC=zh; hy_data_2020_id=1812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff; hy_data_2020_js_sdk=%7B%22distinct_id%22%3A%221812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff%22%2C%22site_id%22%3A457%2C%22user_company%22%3A378%2C%22props%22%3A%7B%7D%2C%22device_id%22%3A%221812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff%22%7D; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%221812140eed513-0dd98f2c5bb2d8-26021b51-2073600-1812140eed6766%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%221812140eed513-0dd98f2c5bb2d8-26021b51-2073600-1812140eed6766%22%7D; Hm_lvt_d6329c2086ec87a286b0b26a49a301c9=1654120312,1654722435; Qs_lvt_326460=1654120311%2C1654722434; Qs_pv_326460=2535230191188450300%2C4074267285746521600; SESSION=YTQyM2M2MzEtYjA4My00MTdkLWIwOTEtNmJjZDZjZDcxNTQ1; i18next=zh; pus=bf25af17-2d37-426f-be36-92150a8db029"


  #=============================================ğŸ‘†testğŸ‘†====================================================


  #=============================================ğŸ‘‡å…¬ç”¨å‚æ•°ğŸ‘‡====================================================

  #è¯·æ±‚å¤´
  headers: { 'Content-Type': 'application/json' }
  'Content-Type-json': 'application/json'
  'Content-Type-form-data': 'application/x-www-form-urlencoded; charset=UTF-8'



