# å˜åŠ¨å‚æ•°ç»Ÿä¸€è®°å½•

#å‚æ•°æ§åˆ¶
parameter:


  #=============================================ğŸ‘‡depğŸ‘‡====================================================
  #ç”Ÿäº§ç¯å¢ƒ

 #     ç”Ÿäº§ç”µè¯å­˜æ”¾åœ°å€
  excelFile: "D:\\263\\20220608å‹æµ‹ç”µè¯.xlsx"
      #è·å–tokené“¾æ¥
  url_token: "https://apipcs.263.net/api/getToken"

      #åˆ›å»ºå€¾å¬ç”µè¯ä¼šè®®é“¾æ¥
  url_create_Meeting: "https://apipcs.263.net/api/createMeeting"

      #è·å–å€¾å¬ç”µè¯ä¼šè®®è¯¦ç»†ä¿¡æ¯é“¾æ¥
  url_query_Meeting: "https://pcs.263.net/meetingRoom/queryMeetingInfo/"

      #å–æ¶ˆä¼šè®®(åªé’ˆå¯¹æœªå¼€å¯æˆ–å·²è¿‡æœŸå¾—å€¾å¬ä¼šè®®)
  url_cancelMeeting: "https://apipcs.263.net/api/cancelMeeting"

      #ç»“æŸä¼šè®®
  ur_endMeeting: "https://pcs.263.net/meetingRoom/endMeeting/"

      #
      #å€¾å¬ç”µè¯ä¼šè®®ä¸»åŠ¨å¤–å‘¼å®¢æˆ·
  url_callParty: "https://pcs.263.net/meetingRoom/control-callParty"

      #å€¾å¬ç”µè¯ä¼šè®®ä¸»åŠ¨æŒ‚æ–­å¤–å‘¼å®¢æˆ·
  url_endcallParty: "https://pcs.263.net/meetingRoom/control-endCallParty"

      #å®¢æˆ·UID
  customerId: "2975223540"

      #å®¢æˆ·å¯†ç 
  secret: "1Te6hb3be0T924f3"

      #åˆ›å»ºä¼šè®®çš„è´¦æˆ·    å¯†ç   net263
  userAccount: "kangyao.xue@net263.com"

  cookie: "anguage=zh; hy_data_2020_id=1812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff; hy_data_2020_js_sdk=%7B%22distinct_id%22%3A%221812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff%22%2C%22site_id%22%3A457%2C%22user_company%22%3A378%2C%22props%22%3A%7B%7D%2C%22device_id%22%3A%221812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff%22%7D; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%221812140eed513-0dd98f2c5bb2d8-26021b51-2073600-1812140eed6766%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%221812140eed513-0dd98f2c5bb2d8-26021b51-2073600-1812140eed6766%22%7D; languageCC=zh; Hm_lvt_d6329c2086ec87a286b0b26a49a301c9=1654120312,1654722435; Qs_lvt_326460=1654120311%2C1654722434; Qs_pv_326460=2535230191188450300%2C4074267285746521600; SESSION=MTk0MTk5NGUtZjIyOS00MTIzLTg3YjktMDdmZmVjZjgzMzQz; i18next=zh; pus=7c008987-3fba-4ef5-8f41-a68999fd5351"
      #userAccount: "xu.chen1@net263"
      #cookie:

      #userAccount: "chen1@net263"
      #cookie:
  #=============================================ğŸ‘†depğŸ‘†====================================================


  #=============================================ğŸ‘‡testğŸ‘‡====================================================
  #æµ‹è¯•ç¯å¢ƒ
#
#  #è™šæ‹Ÿç”µè¯å­˜æ”¾åœ°å€
#  #excelFile: "D:\\263\\æµ‹è¯•è™šæ‹Ÿè´¦å·.xlsx"
#  excelFile: "F:\\263\\æµ‹è¯•è™šæ‹Ÿç”µè¯.xlsx"
#
#  #è·å–tokené“¾æ¥
#  url_token: "https://apipcstest.263.net/api/getToken"
#
#  #åˆ›å»ºå€¾å¬ç”µè¯ä¼šè®®é“¾æ¥
#  url_create_Meeting: "https://apipcstest.263.net/api/createMeeting"
#
#  #è·å–å€¾å¬ç”µè¯ä¼šè®®è¯¦ç»†ä¿¡æ¯é“¾æ¥
#  url_query_Meeting: "https://pcstest.263.net/meetingRoom/queryMeetingInfo/"
#
#  #å–æ¶ˆä¼šè®®(åªé’ˆå¯¹æœªå¼€å¯æˆ–å·²è¿‡æœŸå¾—å€¾å¬ä¼šè®®)
#  url_cancelMeeting: "https://apipcstest.263.net/api/cancelMeeting"
#
#  #ç»“æŸä¼šè®®
#  ur_endMeeting: "https://pcstest.263.net/meetingRoom/endMeeting/"
#
#  #å€¾å¬ç”µè¯ä¼šè®®ä¸»åŠ¨å¤–å‘¼å®¢æˆ·
#  url_callParty: "https://pcstest.263.net/meetingRoom/control-callParty"
#
#  #å€¾å¬ç”µè¯ä¼šè®®ä¸»åŠ¨æŒ‚æ–­å¤–å‘¼å®¢æˆ·
#  url_endcallParty: "https://pcstest.263.net/meetingRoom/control-endCallParty"
#
#  #å®¢æˆ·UID
#  customerId: "U10000247885"
#
#  #å®¢æˆ·å¯†ç 
#  secret: "123456"
#
#  #åˆ›å»ºä¼šè®®çš„è´¦æˆ·
#  userAccount: "xu.chen1@net263.com"
#
#  'cookie': 'language=zh; languageCC=zh; hy_data_2020_id=1812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff; hy_data_2020_js_sdk=%7B%22distinct_id%22%3A%221812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff%22%2C%22site_id%22%3A457%2C%22user_company%22%3A378%2C%22props%22%3A%7B%7D%2C%22device_id%22%3A%221812140eb79361-0860ad6da27c89-26021b51-2073600-1812140eb7a7ff%22%7D; Hm_lvt_d6329c2086ec87a286b0b26a49a301c9=1654120312; Qs_lvt_326460=1654120311; Qs_pv_326460=2535230191188450300; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%221812140eed513-0dd98f2c5bb2d8-26021b51-2073600-1812140eed6766%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%221812140eed513-0dd98f2c5bb2d8-26021b51-2073600-1812140eed6766%22%7D; SESSION=OGQwYTg0YmItNTRiNS00YTRiLWI5ZWItMGQyNWFkNjRhODUx; i18next=zh; pus=522a2dec-a3c5-41e5-ae04-e6fdbe66673b'

  #=============================================ğŸ‘†testğŸ‘†====================================================


  #=============================================ğŸ‘‡å…¬ç”¨å‚æ•°ğŸ‘‡====================================================

  #è¯·æ±‚å¤´
  headers: { 'Content-Type': 'application/json' }
  'Content-Type-json': 'application/json'
  'Content-Type-form-data': 'application/x-www-form-urlencoded; charset=UTF-8'



  #å€¾å¬ä¼šè®®å®šä¹‰å¼€å¯æ—¶é—´
  start_time: 1655401560000
  #start_time_650: 1654614647000



  #åˆ›å»ºå€¾å¬ä¼šè®®æ—¶é•¿  å•ä½min
  duration: 120

  #ç´§æ€¥è”ç³»äºº
  contactList:
    contactName: 3
    contactTelephone: 2
    contactEmail: 1



#    #åˆ›å»ºå€¾å¬ä¼šè®®åœºæ¬¡
#    num : 10
#
#    #åˆ›å»ºå€¾å¬ä¼šè®®æ­¥é•¿
#    step : 2

#    #åˆ›å»ºå€¾å¬,å‘é€æŠ¥å‘Šæ”¶ä»¶äººé‚®ç®±
#    sendEmails: ["cs960515@outlook.com","si.chen@net263.com"]


##é¢„çº¦ä¼šè®®å‚æ•° æ¨¡å¼ä¸€
#Mode:
#    #å…±åˆ›å»ºå¤šå°‘åœºç•…å¬ä¼šè®®
#    num: 220
#    #åœºæ™¯ 1 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_1_num :
#        #æ¨¡å¼ä¸€: æ¥å£åœºæ™¯ä¸º 1 ,å¼€å¯å½•éŸ³,ä¼šä¸­3äºº,ä¼šè®®åœºæ¬¡
#        scene_A: 100
#        #æ¨¡å¼ä¸€: æ¥å£åœºæ™¯ä¸º 1 ,å…³é—­å½•éŸ³,ä¼šä¸­3äºº,ä¼šè®®åœºæ¬¡
#        scene_B: 20
#    #åœºæ™¯4 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_4_num :
#
#        scene_A: 0
#
#        scene_B: 0
#    #åœºæ™¯6 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_6_num :
#        #æ¨¡å¼äºŒ: æ¥å£åœºæ™¯ä¸º 6 ,å…³é—­å½•éŸ³,ä¼šä¸­ 5äºº,è®¢é˜…é¡¾é—®
#        scene_A: 50
#        scene_B: 0
#    #åœºæ™¯7 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_7_num :
#        #æ¨¡å¼äºŒ: æ¥å£åœºæ™¯ä¸º 7 ,å…³é—­å½•éŸ³,ä¼šä¸­ 5äºº,è®¢é˜…å®¢æˆ·
#        scene_A: 50
#        scene_B:

##é¢„çº¦ä¼šè®®å‚æ•° æ¨¡å¼äºŒ
#Mode:
#    #å…±åˆ›å»ºå¤šå°‘åœºç•…å¬ä¼šè®®
#    num: 130
#    #åœºæ™¯ 1 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_1_num :
#        #æ¨¡å¼ä¸€: æ¥å£åœºæ™¯ä¸º 1 ,ä¼šä¸­3äºº,ä¼šè®®åœºæ¬¡
#        scene_A: 39
#        #æ¨¡å¼ä¸€: æ— æ­¤æƒ…å†µ
#        scene_B: 0
#    #åœºæ™¯4 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_4_num :
#        # æ¥å£åœºæ™¯ä¸º4,ä¼šä¸­3äºº,ä¸å½•éŸ³
#        scene_A: 50
#
#        scene_B: 0
#    #åœºæ™¯6 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_6_num :
#        #æ¨¡å¼äºŒ: æ¥å£åœºæ™¯ä¸º 6 ,å…³é—­å½•éŸ³,ä¼šä¸­ 5äºº,è®¢é˜…é¡¾é—®
#        scene_A: 20
#        scene_B: 0
#    #åœºæ™¯7 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_7_num :
#        #æ¨¡å¼äºŒ: æ¥å£åœºæ™¯ä¸º 7 ,å…³é—­å½•éŸ³,ä¼šä¸­ 5äºº,è®¢é˜…å®¢æˆ·
#        scene_A: 20
#        scene_B:

