# å˜åŠ¨å‚æ•°ç»Ÿä¸€è®°å½•

#å‚æ•°æ§åˆ¶
parameter:


#=============================================ğŸ‘‡depğŸ‘‡====================================================
    #ç”Ÿäº§ç¯å¢ƒ

#    ç”Ÿäº§ç”µè¯å­˜æ”¾åœ°å€
#    dep_excelFile: "F:\\263\\ç”µè¯.xlsx"
#    #è·å–tokené“¾æ¥
#    url_token: "https://apipcs.263.net/api/getToken"
#
#    #åˆ›å»ºå€¾å¬ç”µè¯ä¼šè®®é“¾æ¥
#    url_create_Meeting: "https://apipcs.263.net/api/createMeeting"
#
#    #è·å–å€¾å¬ç”µè¯ä¼šè®®è¯¦ç»†ä¿¡æ¯é“¾æ¥
#    url_query_Meeting: "https://pcs.263.net/meetingRoom/queryMeetingInfo/"
#
#    #å–æ¶ˆä¼šè®®(åªé’ˆå¯¹æœªå¼€å¯æˆ–å·²è¿‡æœŸå¾—å€¾å¬ä¼šè®®)
#    url_cancelMeeting: "https://apipcs.263.net/api/cancelMeeting"
#
#    #ç»“æŸä¼šè®®
#    ur_endMeeting: "https://pcs.263.net/meetingRoom/endMeeting/"
#
#    #
#    #å€¾å¬ç”µè¯ä¼šè®®ä¸»åŠ¨å¤–å‘¼å®¢æˆ·
#    url_callParty: "https://pcs.263.net/meetingRoom/control-callParty"
#
#    #å®¢æˆ·UID
#    customerId: "U11001346548"
#
#    #å®¢æˆ·å¯†ç 
#    secret: "WiOroBTHdM1U6wwukO9Y7EzD927nVrhZ"
#
#    #åˆ›å»ºä¼šè®®çš„è´¦æˆ·    å¯†ç   net263
#    userAccount: "cx@net263.com"
#=============================================ğŸ‘†depğŸ‘†====================================================


#=============================================ğŸ‘‡testğŸ‘‡====================================================
    #æµ‹è¯•ç¯å¢ƒ

    #è™šæ‹Ÿç”µè¯å­˜æ”¾åœ°å€
    excelFile: "D:\\263\\æµ‹è¯•è™šæ‹Ÿè´¦å·.xlsx"

    #è·å–tokené“¾æ¥
    url_token: "https://apipcstest.263.net/api/getToken"

    #åˆ›å»ºå€¾å¬ç”µè¯ä¼šè®®é“¾æ¥
    url_create_Meeting: "https://apipcstest.263.net/api/createMeeting"

    #è·å–å€¾å¬ç”µè¯ä¼šè®®è¯¦ç»†ä¿¡æ¯é“¾æ¥
    url_query_Meeting: "https://pcstest.263.net/meetingRoom/queryMeetingInfo/"

    #å–æ¶ˆä¼šè®®(åªé’ˆå¯¹æœªå¼€å¯æˆ–å·²è¿‡æœŸå¾—å€¾å¬ä¼šè®®)
    url_cancelMeeting:  "https://apipcstest.263.net/api/cancelMeeting"

    #ç»“æŸä¼šè®®
    ur_endMeeting:  "https://pcstest.263.net/meetingRoom/endMeeting/"

    #å€¾å¬ç”µè¯ä¼šè®®ä¸»åŠ¨å¤–å‘¼å®¢æˆ·
    url_callParty: "https://pcstest.263.net/meetingRoom/control-callParty"

    #å®¢æˆ·UID
    customerId: "U10000247885"

    #å®¢æˆ·å¯†ç 
    secret: "123456"

    #åˆ›å»ºä¼šè®®çš„è´¦æˆ·
    userAccount: "xu.chen1@net263.com"

#=============================================ğŸ‘†testğŸ‘†====================================================


#=============================================ğŸ‘‡å…¬ç”¨å‚æ•°ğŸ‘‡====================================================

    #è¯·æ±‚å¤´
    headers: {'Content-Type': 'application/json'}
    'Content-Type-json': 'application/json'
    'Content-Type-form-data': 'application/x-www-form-urlencoded; charset=UTF-8'
    'cookie': 'language=zh; SESSION=ZGY2NTYxOTAtN2QwOC00MzFhLTg2NTItOGRmNDRjNzQ3Nzc2; languageCC=zh; i18next=zh; pus=14bd8b18-b929-4c9c-b76d-ca30a8c13ec1'


    #å€¾å¬ä¼šè®®å®šä¹‰å¼€å¯æ—¶é—´
    start_time: 1654086600000

    #ä¼šè®®ä½¿ç”¨è™šæ‹Ÿè´¦å·åœ°å€   æ–‡æ¡£å†…çš„æ ¼å¼å¿…é¡»å›ºå®š,å†™æ­»äº†,è¦æœ‰ 5ä¸ªsheetè¡¨,ç¡®ä¿ç´¢å¼•ä¸è¶Šç•Œ
    #excelFile: "D:\\263\\æµ‹è¯•è™šæ‹Ÿè´¦å·.xlsx"


    #åˆ›å»ºå€¾å¬ä¼šè®®æ—¶é•¿  å•ä½min
    duration: 120

    #ç´§æ€¥è”ç³»äºº
    contactList:
        contactName: 3
        contactTelephone: 2
        contactEmail: 1



#    #åˆ›å»ºå€¾å¬ä¼šè®®åœºæ¬¡
#    num : 10
#
#    #åˆ›å»ºå€¾å¬ä¼šè®®æ­¥é•¿
#    step : 2

#    #åˆ›å»ºå€¾å¬,å‘é€æŠ¥å‘Šæ”¶ä»¶äººé‚®ç®±
#    sendEmails: ["cs960515@outlook.com","si.chen@net263.com"]


##é¢„çº¦ä¼šè®®å‚æ•° æ¨¡å¼ä¸€
#Mode:
#    #å…±åˆ›å»ºå¤šå°‘åœºç•…å¬ä¼šè®®
#    num: 220
#    #åœºæ™¯ 1 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_1_num :
#        #æ¨¡å¼ä¸€: æ¥å£åœºæ™¯ä¸º 1 ,å¼€å¯å½•éŸ³,ä¼šä¸­3äºº,ä¼šè®®åœºæ¬¡
#        scene_A: 100
#        #æ¨¡å¼ä¸€: æ¥å£åœºæ™¯ä¸º 1 ,å…³é—­å½•éŸ³,ä¼šä¸­3äºº,ä¼šè®®åœºæ¬¡
#        scene_B: 20
#    #åœºæ™¯4 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_4_num :
#
#        scene_A: 0
#
#        scene_B: 0
#    #åœºæ™¯6 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_6_num :
#        #æ¨¡å¼äºŒ: æ¥å£åœºæ™¯ä¸º 6 ,å…³é—­å½•éŸ³,ä¼šä¸­ 5äºº,è®¢é˜…é¡¾é—®
#        scene_A: 50
#        scene_B: 0
#    #åœºæ™¯7 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_7_num :
#        #æ¨¡å¼äºŒ: æ¥å£åœºæ™¯ä¸º 7 ,å…³é—­å½•éŸ³,ä¼šä¸­ 5äºº,è®¢é˜…å®¢æˆ·
#        scene_A: 50
#        scene_B:

##é¢„çº¦ä¼šè®®å‚æ•° æ¨¡å¼äºŒ
#Mode:
#    #å…±åˆ›å»ºå¤šå°‘åœºç•…å¬ä¼šè®®
#    num: 130
#    #åœºæ™¯ 1 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_1_num :
#        #æ¨¡å¼ä¸€: æ¥å£åœºæ™¯ä¸º 1 ,ä¼šä¸­3äºº,ä¼šè®®åœºæ¬¡
#        scene_A: 39
#        #æ¨¡å¼ä¸€: æ— æ­¤æƒ…å†µ
#        scene_B: 0
#    #åœºæ™¯4 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_4_num :
#        # æ¥å£åœºæ™¯ä¸º4,ä¼šä¸­3äºº,ä¸å½•éŸ³
#        scene_A: 50
#
#        scene_B: 0
#    #åœºæ™¯6 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_6_num :
#        #æ¨¡å¼äºŒ: æ¥å£åœºæ™¯ä¸º 6 ,å…³é—­å½•éŸ³,ä¼šä¸­ 5äºº,è®¢é˜…é¡¾é—®
#        scene_A: 20
#        scene_B: 0
#    #åœºæ™¯7 åˆ›å»ºçš„ä¼šè®®åœºæ¬¡
#    callOutType_7_num :
#        #æ¨¡å¼äºŒ: æ¥å£åœºæ™¯ä¸º 7 ,å…³é—­å½•éŸ³,ä¼šä¸­ 5äºº,è®¢é˜…å®¢æˆ·
#        scene_A: 20
#        scene_B:

